def awsECRURL="347880001135.dkr.ecr.ap-northeast-2.amazonaws.com/test"
def awsKey="aws-key"
def awsRegion="ap-northeast-2"
def branch="master"
def commitMsg="mini-project"
def directoryPath="Part4_Kubernetes/Chapter11/mini-project/service"
def githubEmail="skwjdgh1@gmail.com"
def githubKey="github-key"
def githubSSHURL="git@github.com:Najeongho/FastCampus.git"
def imageTag="red"

podTemplate(label: 'docker-build', serviceAccount: "jenkins", namespace: "jenkins", runAsUser: "0",
  containers: [
    containerTemplate(
      name: 'docker',
      image: 'docker:20.10.7',
      ttyEnabled: true,
      command: 'cat'
    ),
    containerTemplate(
      name: 'argo',
      image: 'argoproj/argo-cd-ci-builder:latest',
      ttyEnabled: true,
      command: 'cat'
    ),
  ],
  volumes: [ 
    //hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock'),
    hostPathVolume(hostPath: '/etc/hosts', mountPath: '/etc/hosts')
  ]
) {
  node('docker-build') {

		stage('Checkout') {
            container('docker'){
                checkout scm
            }
		}

		stage('Docker Build') {
			dir(path: "${directoryPath}/container"){
				container('docker') {
					image = docker.build("${awsECRURL}:${imageTag}","--build-arg COLOR=${imageTag} .")
				}
			}
		}

		stage('ECR Push') {
			container('docker') {
				docker.withRegistry("https://${awsECRURL}", "ecr:${awsRegion}:${awsKey}") {
					image.push()
				}
			}
		}

        stage('Deploy'){
            container('argo'){
                checkout(
                    [
                        $class: 'GitSCM',
                        extensions: scm.extensions,
                        branches: [
                            [
                                name: "*/${branch}"
                            ]
                        ],
                        userRemoteConfigs: [
                            [
                                url: "${githubSSHURL}",
                                credentialsId: "${githubKey}",
                            ]
                        ]
                    ]
                )
                sshagent(credentials: ["${githubKey}"]){
                    sh("""
                        #!/usr/bin/env bash
                        set +x
                        export GIT_SSH_COMMAND="ssh -oStrictHostKeyChecking=no"
                        git config --global user.email ${githubEmail}
                        git checkout ${branch}
                        cd ${directoryPath}/helm-charts
                        sed -i 's/tag:.*/tag: ${imageTag}/g' values.yaml
                        cd ../../../../
                        git commit -a -m ${commitMsg}
                        git remote set-url origin ${githubSSHURL}
                        git push -u origin master
                    """)
                }
            }
        }		
	}
}